-   id: checkstyle
    name: Checkstyle Java Code
    description: This hook checkstyle the code style.
    #entry: runCheckstyle.sh
    entry: runCheckstylePerl
    language: script
    types: [text]
